
target 'Visual_Example' do
   pod 'Visual', :path => '../'

   pod 'VisualParser', :git => 'https://github.com/TENQUBE/VisualParser.git'
   pod 'Realm', '~> 3.18.0', :modular_headers => true
  
   pod 'RealmSwift', '~> 3.18.0', :modular_headers => true
#  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
#  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
 target 'Visual_Tests' do
    inherit! :search_paths

    
  end
end
